#!/usr/bin/env bash
# W2(dev-preview) media derivation — 2026-09-15
# Rules: originals are NEVER modified; outputs are new files under public/media.
# Operations: re-encode (libx264, no audio) and lossless-layout compositing of
# existing per-view files. No content edits, no generative fill, no interpolation,
# no speed changes. All source paths and commands are recorded in
# reports/media-derivation-record.md (generated by this script).
set -euo pipefail

ROOT="."
if [[ "${1:-}" == "--adaptation-gaps" ]]; then
  exec bash "$ROOT/scripts/prepare_adaptation_gaps.sh"
fi
if [[ "${1:-}" == "--libero-equal-views" ]]; then
  exec bash "$ROOT/scripts/prepare_libero_equal_views.sh"
fi
if [[ "${1:-}" == "--temporal-ceiling" ]]; then
  exec bash "$ROOT/scripts/prepare_temporal_media.sh"
fi
MEDIA="$ROOT/public/media/rollouts"
POSTERS="$ROOT/public/media/posters"
FIGS="$ROOT/public/media/figures"
LOG="$ROOT/reports/media-derivation-record.md"
mkdir -p "$MEDIA" "$POSTERS" "$FIGS"

SP="../demo_wm_generate_sp"
BASE="../demo_wm_generated"
PAPER_FIG="../iclr2027-mixworld/figure"

MOBILE="$SP/new_studyroom_mobile_fold_socks/episode_0001"
FIXED="$SP/static_yam_socks/episode_0001"
HUM="$BASE/humanoid/037_wbt_unitreerobotics__G1_WBT_Brainco_Pickup_Pillow_unitree_wbt__unitreerobotics__G1_WBT_Brainco_Pickup_Pillow__episode_280_full"

ENC="-c:v libx264 -preset veryfast -crf 24 -pix_fmt yuv420p -movflags +faststart -an"

{
echo "# 媒体派生记录（开发预览批）"
echo "日期: $(date '+%F %T') · 原则: 只转码/拼版, 不改内容, 原件只读"
echo
echo "| 输出 | 源 | 命令要点 |"
echo "|---|---|---|"
} > "$LOG"

log_derive () {
  echo "| $1 | $2 | $3 |" >> "$LOG"
}

# idempotent: skip an output that already exists (script is re-runnable)
skip_if_exists () {
  if [ -s "$1" ]; then
    echo "skip (exists): $1"
    return 0
  fi
  return 1
}

# 1. Mobile prediction composite (native 3328x896 layout preserved)
out="$MEDIA/gallery_mobile_01__mix-pred__multiview__full.mp4"
skip_if_exists "$out" ||
ffmpeg -v error -y -i "$MOBILE/generated_three_view.mp4" -vf "scale=2560:-2" $ENC "$out"
log_derive "$out" "$MOBILE/generated_three_view.mp4" "re-encode libx264 crf24, scale 3328x896 -> 2560x688 (-2 rounding), audio stripped"

# 2. Mobile reference composite
out="$MEDIA/gallery_mobile_01__reference__multiview__full.mp4"
skip_if_exists "$out" ||
ffmpeg -v error -y -i "$MOBILE/gt.mp4" -vf "scale=2560:-2" $ENC "$out"
log_derive "$out" "$MOBILE/gt.mp4" "re-encode libx264 crf24, scale 3328x896 -> 2560x688, audio stripped"

# 3. Fixed-arm prediction composite: cam_high | vstack(left_wrist, right_wrist)
#    mirrors the recorded gt composite structure (big view left, two stacked right)
out="$MEDIA/gallery_fixed_01__mix-pred__multiview__full.mp4"
skip_if_exists "$out" ||
ffmpeg -v error -y -i "$FIXED/cam_high.mp4" -i "$FIXED/cam_left_wrist.mp4" -i "$FIXED/cam_right_wrist.mp4" \
  -filter_complex "[1:v][2:v]vstack=inputs=2[w];[0:v][w]hstack=inputs=2" $ENC "$out"
log_derive "$out" "$FIXED/cam_high.mp4 + cam_left_wrist.mp4 + cam_right_wrist.mp4" "layout compose hstack(high, vstack(lw,rw)) -> 2560x1152, then re-encode crf24; layout mirrors gt composite"

# 4. Fixed-arm reference composite
out="$MEDIA/gallery_fixed_01__reference__multiview__full.mp4"
skip_if_exists "$out" ||
ffmpeg -v error -y -i "$FIXED/gt.mp4" $ENC "$out"
log_derive "$out" "$FIXED/gt.mp4" "re-encode libx264 crf24, native 2560x1152, audio stripped"

# 5. Humanoid prediction composite: 576x288 canvas per documented view-split design
#    cam_high 384x288 @(0,0); left_wrist 192x144 @(384,0); right_wrist 192x144 @(384,144)
out="$MEDIA/gallery_humanoid_01__mix-pred__multiview__full.mp4"
skip_if_exists "$out" ||
ffmpeg -v error -y -i "$HUM/cam_high.mp4" -i "$HUM/cam_left_wrist.mp4" -i "$HUM/cam_right_wrist.mp4" \
  -filter_complex "[1:v][2:v]vstack=inputs=2[rcol];[0:v][rcol]hstack=inputs=2" $ENC "$out"
log_derive "$out" "$HUM/cam_high.mp4 + cam_left_wrist.mp4 + cam_right_wrist.mp4" "tile hstack(high 384x288, vstack(lw 192x144, rw 192x144)) -> 576x288 per docs/superpowers/specs/2026-08-04-production-generated-view-split-design.md; finite inputs only (no color source), native res, no upscale"

# Posters = first frame of each derived video (same experiment as the video)
for f in "$MEDIA"/*.mp4; do
  base=$(basename "$f" .mp4)
  skip_if_exists "$POSTERS/$base.poster.jpg" ||
  ffmpeg -v error -y -i "$f" -frames:v 1 -q:v 3 "$POSTERS/$base.poster.jpg"
done
log_derive "public/media/posters/*.poster.jpg" "each derived mp4" "first-frame JPEG q3"

# Interim paper figures (owner-approved placeholder policy for missing videos)
cp "$PAPER_FIG/fig_action_control_fixed_socks_readable.png" "$FIGS/fig4_action_conditions_readable.png"
cp "$PAPER_FIG/fig_cross_embodiment_adaptation_refined.png" "$FIGS/fig5_cross_embodiment_adaptation_refined.png"
cp "$PAPER_FIG/fig_method_overview.png" "$FIGS/fig2_method_overview.png"
cp "$PAPER_FIG/fig_pretraining_embodiments.png" "$FIGS/fig_pretraining_embodiments.png"
log_derive "public/media/figures/*.png" "$PAPER_FIG/... (4 files)" "byte-identical copies, renamed; used as labeled placeholders for missing videos"

echo
echo "## 派生产物清单" >> "$LOG"
ls -la "$MEDIA" "$POSTERS" "$FIGS" >> "$LOG"
echo "DONE"

# 6. Humanoid long-rollout composite (paper Fig.1 case, 146.4 s @10fps)
#    ce_h02 ego 384x288 + left/right wrist 192x144 -> 576x288 tile
CW="~/Downloads/placeholder-source_videos"
out="$MEDIA/gallery_humanoid_long__mix-pred__multiview__full.mp4"
skip_if_exists "$out" ||
ffmpeg -v error -y -i "$CW/ce_h02_ego_h264_54be4bb8.mp4" -i "$CW/ce_h02_left_h264_e3781ead.mp4" -i "$CW/ce_h02_right_h264_d052bcc1.mp4" \
  -filter_complex "[1:v][2:v]vstack=inputs=2[rcol];[0:v][rcol]hstack=inputs=2" $ENC "$out"
log_derive "$out" "$CW/ce_h02_{ego,left,right}_*.mp4 (team-owned, user-confirmed 2026-09-15)" "tile hstack(ego 384x288, vstack(l,r) 192x144) -> 576x288; re-encode crf24; rights: team blog assets, formal approval still pending"
